"""
Database type definitions for Supabase.
Keep in sync with supabase/migrations/*.sql
"""

from typing import TypedDict, Optional


class UserRow(TypedDict):
    id: str
    email: str
    created_at: str


class ProfileRow(TypedDict):
    user_id: str
    college_tier: Optional[str]
    branch: Optional[str]
    grad_year: Optional[int]
    target_roles: list[str]
    weekday_hrs: Optional[int]
    weekend_hrs: Optional[int]
    preferred_windows: list[str]
    skill_levels: Optional[dict]
    is_pro: bool
    pro_expires_at: Optional[str]
    telegram_chat_id: Optional[str]
    updated_at: Optional[str]


class ScheduleRow(TypedDict):
    id: str
    user_id: str
    generated_at: str
    status: str  # 'active' | 'completed' | 'rescued'


class ScheduleItemRow(TypedDict):
    id: str
    schedule_id: str
    day_index: int
    time_slot: str
    topic: str
    difficulty: str
    resource_url: str
    status: str  # 'pending' | 'completed' | 'skipped'
    updated_at: Optional[str]


class PaymentRow(TypedDict):
    id: str
    user_id: str
    stripe_session_id: Optional[str]
    amount_paisa: int
    currency: str
    status: str  # 'pending' | 'success' | 'failed'
    created_at: str


# Supabase JS SDK generic Database type
Database = dict  # Placeholder — full type generated by `supabase gen types typescript`
